services:
  company-db:
    image: postgres:16-alpine
    container_name: company-db
    environment:
      environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: company_registry
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: