spring.datasource.url=jdbc:postgresql://localhost:5433/company_registry
spring.datasource.username=admin
spring.datasource.password=admin123

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always